name: Commit File to Master

on:
  push:
    branches:
      - main  # Replace with the default branch of your repository

jobs:
  commit_file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run cagri.sh
        run: bash cagri.sh
      - name: Commit file
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add .
          git commit -m "Add generated file"
          git push origin main  # Replace with the default branch of your repository
